### ISSUE TITLE
Add lightnet Docker image for tests instead of relying on live network

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/Archive-Node-API#95]
# Summary
Currently, we use a live network (in this case Berkeley) for our benchmarking tests. This requires zkApps to always be deployed if we want to run our benchmarks, and with network restarts, we constantly have to redeploy.

Instead, we can use the [local network](https://hub.docker.com/r/o1labs/mina-local-network) docker image to deploy a zkApp, and then run benchmarks against it. This will always be reproducible and easier to maintain

**Comment by shimkiv** [comment]
This is how you usually configure helper service for the GH Actions: https://github.com/o1-labs/o1js/blob/084a1e7338bd8d345ec48ae722cfd8f06bcdaa92/.github/workflows/live-tests.yml#L70
And this is an example of waiting for the network readiness on GitHub CI: https://github.com/o1-labs/o1js/blob/084a1e7338bd8d345ec48ae722cfd8f06bcdaa92/.github/actions/live-tests-shared/action.yml#L10
